### ISSUE TITLE
ffuf not installing

### ISSUE THREAD

**Issue by dhjensen** [marcinbojko/linux_mint#2]
Unpacking ffuf archive is not producing any files during the playbook run.

Adding PR

**Comment by marcinbojko** [comment]
I decided to rework download part, which was bugging me for a long time.
Fixed by: https://github.com/marcinbojko/linux_mint/commit/c7f2b3db5d02072935cbcf688ba0fabfbfcb68d8

**Comment by dhjensen** [comment]
thx, works
